const SHOW_MODAL_SIGNIN = "SHOW_MODAL_SIGNIN";
const HIDE_MODAL_SIGNIN = "HIDE_MODAL_SIGNIN";

const SHOW_MODAL_SIGNUP = "SHOW_MODAL_SIGNUP";
const HIDE_MODAL_SIGNUP = "HIDE_MODAL_SIGNUP";
export {
  SHOW_MODAL_SIGNIN,
  HIDE_MODAL_SIGNIN,
  SHOW_MODAL_SIGNUP,
  HIDE_MODAL_SIGNUP,
};
