
export const GET_LISTROOM = "GET_LISTROOM";
export const FILTER_ROOM = "FILTER_ROOM";
export const FILTER_PRICE = "FILTER_ROOM";
export const OPEN_MODAL_FILTER = "OPEN_MODAL_FILTER";
export const CLOSE_MODAL_FILTER = "CLOSE_MODAL_FILTER";
